#############################################################################
# Makefile for building: libqmlmusicplugin.so
# Generated by qmake (2.01a) (Qt 4.7.3) on: Tue Dec 20 04:21:18 2011
# Project:  qmlmusicplugin.pro
# Template: lib
# Command: /usr/bin/qmake -o Makefile qmlmusicplugin.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_PLUGIN -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -D_REENTRANT -Wall -W -fPIC $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtDeclarative -I/usr/include/qt4 -I/usr/include/qt4/QtDBus -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1 -shared
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtDBus -lQtDeclarative -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = sourcemanager.cpp \
		mpris2tracklistproxy.cpp \
		mprisrootproxy.cpp \
		mpris2rootproxy.cpp \
		mpris2playerproxy.cpp \
		mprisplayerproxy.cpp \
		mprissource.cpp \
		mprisstatus.cpp \
		player.cpp \
		qmlmusicplugin.cpp \
		source.cpp \
		mpris2source.cpp \
		auxsource.cpp \
		tracksource.cpp moc_sourceoption.cpp \
		moc_mpris2tracklistproxy.cpp \
		moc_mprisrootproxy.cpp \
		moc_mpris2rootproxy.cpp \
		moc_mpris2playerproxy.cpp \
		moc_mpris2source.cpp \
		moc_mprisplayerproxy.cpp \
		moc_mprissource.cpp \
		moc_player.cpp \
		moc_qmlmusicplugin.cpp \
		moc_source.cpp \
		moc_vlcsource.cpp \
		moc_spotifysource.cpp \
		moc_bansheesource.cpp \
		moc_auxsource.cpp \
		moc_tracksource.cpp
OBJECTS       = sourcemanager.o \
		mpris2tracklistproxy.o \
		mprisrootproxy.o \
		mpris2rootproxy.o \
		mpris2playerproxy.o \
		mprisplayerproxy.o \
		mprissource.o \
		mprisstatus.o \
		player.o \
		qmlmusicplugin.o \
		source.o \
		mpris2source.o \
		auxsource.o \
		tracksource.o \
		moc_sourceoption.o \
		moc_mpris2tracklistproxy.o \
		moc_mprisrootproxy.o \
		moc_mpris2rootproxy.o \
		moc_mpris2playerproxy.o \
		moc_mpris2source.o \
		moc_mprisplayerproxy.o \
		moc_mprissource.o \
		moc_player.o \
		moc_qmlmusicplugin.o \
		moc_source.o \
		moc_vlcsource.o \
		moc_spotifysource.o \
		moc_bansheesource.o \
		moc_auxsource.o \
		moc_tracksource.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qdbus.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		qmlmusicplugin.pro
QMAKE_TARGET  = qmlmusicplugin
DESTDIR       = music/
TARGET        = libqmlmusicplugin.so
TARGETD       = libqmlmusicplugin.so

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile  music/$(TARGET)

music/$(TARGET):  $(OBJECTS) $(SUBLIBS) $(OBJCOMP)  
	@$(CHK_DIR_EXISTS) music/ || $(MKDIR) music/ 
	-$(DEL_FILE) $(TARGET)
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS) $(OBJCOMP)
	-$(MOVE) $(TARGET) music/



Makefile: qmlmusicplugin.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qdbus.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/dbusinterfaces.prf \
		/usr/share/qt4/mkspecs/features/dbusadaptors.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtDBus.prl \
		/usr/lib/libQtDeclarative.prl \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -o Makefile qmlmusicplugin.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qdbus.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/dbusinterfaces.prf:
/usr/share/qt4/mkspecs/features/dbusadaptors.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtDBus.prl:
/usr/lib/libQtDeclarative.prl:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile qmlmusicplugin.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/qmlmusicplugin1.0.0 || $(MKDIR) .tmp/qmlmusicplugin1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/qmlmusicplugin1.0.0/ && $(COPY_FILE) --parents sourcemanager.h sourceoption.h mpris2tracklistproxy.h mprisrootproxy.h mpris2rootproxy.h mpris2playerproxy.h mpris2source.h mprisplayerproxy.h mprissource.h mprisstatus.h player.h qmlmusicplugin.h source.h vlcsource.h spotifysource.h bansheesource.h auxsource.h tracksource.h papafactory/details.h papafactory/factory.h papafactory/papa_exception.h papafactory/phactory.h papafactory/singleton.h papafactory/staticfactory.h .tmp/qmlmusicplugin1.0.0/ && $(COPY_FILE) --parents sourcemanager.cpp mpris2tracklistproxy.cpp mprisrootproxy.cpp mpris2rootproxy.cpp mpris2playerproxy.cpp mprisplayerproxy.cpp mprissource.cpp mprisstatus.cpp player.cpp qmlmusicplugin.cpp source.cpp mpris2source.cpp auxsource.cpp tracksource.cpp .tmp/qmlmusicplugin1.0.0/ && (cd `dirname .tmp/qmlmusicplugin1.0.0` && $(TAR) qmlmusicplugin1.0.0.tar qmlmusicplugin1.0.0 && $(COMPRESS) qmlmusicplugin1.0.0.tar) && $(MOVE) `dirname .tmp/qmlmusicplugin1.0.0`/qmlmusicplugin1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/qmlmusicplugin1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_sourceoption.cpp moc_mpris2tracklistproxy.cpp moc_mprisrootproxy.cpp moc_mpris2rootproxy.cpp moc_mpris2playerproxy.cpp moc_mpris2source.cpp moc_mprisplayerproxy.cpp moc_mprissource.cpp moc_player.cpp moc_qmlmusicplugin.cpp moc_source.cpp moc_vlcsource.cpp moc_spotifysource.cpp moc_bansheesource.cpp moc_auxsource.cpp moc_tracksource.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_sourceoption.cpp moc_mpris2tracklistproxy.cpp moc_mprisrootproxy.cpp moc_mpris2rootproxy.cpp moc_mpris2playerproxy.cpp moc_mpris2source.cpp moc_mprisplayerproxy.cpp moc_mprissource.cpp moc_player.cpp moc_qmlmusicplugin.cpp moc_source.cpp moc_vlcsource.cpp moc_spotifysource.cpp moc_bansheesource.cpp moc_auxsource.cpp moc_tracksource.cpp
moc_sourceoption.cpp: sourceoption.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) sourceoption.h -o moc_sourceoption.cpp

moc_mpris2tracklistproxy.cpp: mpris2tracklistproxy.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mpris2tracklistproxy.h -o moc_mpris2tracklistproxy.cpp

moc_mprisrootproxy.cpp: mprisrootproxy.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mprisrootproxy.h -o moc_mprisrootproxy.cpp

moc_mpris2rootproxy.cpp: mpris2rootproxy.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mpris2rootproxy.h -o moc_mpris2rootproxy.cpp

moc_mpris2playerproxy.cpp: mpris2playerproxy.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mpris2playerproxy.h -o moc_mpris2playerproxy.cpp

moc_mpris2source.cpp: tracksource.h \
		source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h \
		mpris2playerproxy.h \
		mpris2rootproxy.h \
		mpris2tracklistproxy.h \
		mpris2source.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mpris2source.h -o moc_mpris2source.cpp

moc_mprisplayerproxy.cpp: mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h \
		mprisplayerproxy.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mprisplayerproxy.h -o moc_mprisplayerproxy.cpp

moc_mprissource.cpp: tracksource.h \
		source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h \
		mprisplayerproxy.h \
		mprisrootproxy.h \
		mprissource.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mprissource.h -o moc_mprissource.cpp

moc_player.cpp: source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		sourcemanager.h \
		player.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) player.h -o moc_player.cpp

moc_qmlmusicplugin.cpp: player.h \
		source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		sourcemanager.h \
		mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h \
		qmlmusicplugin.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) qmlmusicplugin.h -o moc_qmlmusicplugin.cpp

moc_source.cpp: papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		source.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) source.h -o moc_source.cpp

moc_vlcsource.cpp: mprissource.h \
		tracksource.h \
		source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h \
		mprisplayerproxy.h \
		mprisrootproxy.h \
		vlcsource.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) vlcsource.h -o moc_vlcsource.cpp

moc_spotifysource.cpp: mpris2source.h \
		tracksource.h \
		source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h \
		mpris2playerproxy.h \
		mpris2rootproxy.h \
		mpris2tracklistproxy.h \
		spotifysource.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) spotifysource.h -o moc_spotifysource.cpp

moc_bansheesource.cpp: mpris2source.h \
		tracksource.h \
		source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h \
		mpris2playerproxy.h \
		mpris2rootproxy.h \
		mpris2tracklistproxy.h \
		bansheesource.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) bansheesource.h -o moc_bansheesource.cpp

moc_auxsource.cpp: source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		auxsource.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) auxsource.h -o moc_auxsource.cpp

moc_tracksource.cpp: source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		tracksource.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) tracksource.h -o moc_tracksource.cpp

compiler_dbus_interface_source_make_all:
compiler_dbus_interface_source_clean:
compiler_dbus_adaptor_source_make_all:
compiler_dbus_adaptor_source_clean:
compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_interface_header_make_all:
compiler_dbus_interface_header_clean:
compiler_dbus_interface_moc_make_all:
compiler_dbus_interface_moc_clean:
compiler_dbus_adaptor_header_make_all:
compiler_dbus_adaptor_header_clean:
compiler_dbus_adaptor_moc_make_all:
compiler_dbus_adaptor_moc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

sourcemanager.o: sourcemanager.cpp sourcemanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sourcemanager.o sourcemanager.cpp

mpris2tracklistproxy.o: mpris2tracklistproxy.cpp mpris2tracklistproxy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpris2tracklistproxy.o mpris2tracklistproxy.cpp

mprisrootproxy.o: mprisrootproxy.cpp mprisrootproxy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mprisrootproxy.o mprisrootproxy.cpp

mpris2rootproxy.o: mpris2rootproxy.cpp mpris2rootproxy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpris2rootproxy.o mpris2rootproxy.cpp

mpris2playerproxy.o: mpris2playerproxy.cpp mpris2playerproxy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpris2playerproxy.o mpris2playerproxy.cpp

mprisplayerproxy.o: mprisplayerproxy.cpp mprisplayerproxy.h \
		mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mprisplayerproxy.o mprisplayerproxy.cpp

mprissource.o: mprissource.cpp mprissource.h \
		tracksource.h \
		source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h \
		mprisplayerproxy.h \
		mprisrootproxy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mprissource.o mprissource.cpp

mprisstatus.o: mprisstatus.cpp mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mprisstatus.o mprisstatus.cpp

player.o: player.cpp papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		player.h \
		source.h \
		sourceoption.h \
		sourcemanager.h \
		vlcsource.h \
		mprissource.h \
		tracksource.h \
		mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h \
		mprisplayerproxy.h \
		mprisrootproxy.h \
		mpris2source.h \
		mpris2playerproxy.h \
		mpris2rootproxy.h \
		mpris2tracklistproxy.h \
		bansheesource.h \
		spotifysource.h \
		auxsource.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o player.cpp

qmlmusicplugin.o: qmlmusicplugin.cpp qmlmusicplugin.h \
		player.h \
		source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		sourcemanager.h \
		mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmlmusicplugin.o qmlmusicplugin.cpp

source.o: source.cpp source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o source.o source.cpp

mpris2source.o: mpris2source.cpp mpris2source.h \
		tracksource.h \
		source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h \
		mprisstatus.h \
		/usr/include/qt4/Qt/qdbusargument.h \
		mpris2playerproxy.h \
		mpris2rootproxy.h \
		mpris2tracklistproxy.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mpris2source.o mpris2source.cpp

auxsource.o: auxsource.cpp auxsource.h \
		source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o auxsource.o auxsource.cpp

tracksource.o: tracksource.cpp tracksource.h \
		source.h \
		papafactory/factory.h \
		papafactory/singleton.h \
		papafactory/details.h \
		papafactory/papa_exception.h \
		sourceoption.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tracksource.o tracksource.cpp

moc_sourceoption.o: moc_sourceoption.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sourceoption.o moc_sourceoption.cpp

moc_mpris2tracklistproxy.o: moc_mpris2tracklistproxy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpris2tracklistproxy.o moc_mpris2tracklistproxy.cpp

moc_mprisrootproxy.o: moc_mprisrootproxy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mprisrootproxy.o moc_mprisrootproxy.cpp

moc_mpris2rootproxy.o: moc_mpris2rootproxy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpris2rootproxy.o moc_mpris2rootproxy.cpp

moc_mpris2playerproxy.o: moc_mpris2playerproxy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpris2playerproxy.o moc_mpris2playerproxy.cpp

moc_mpris2source.o: moc_mpris2source.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mpris2source.o moc_mpris2source.cpp

moc_mprisplayerproxy.o: moc_mprisplayerproxy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mprisplayerproxy.o moc_mprisplayerproxy.cpp

moc_mprissource.o: moc_mprissource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mprissource.o moc_mprissource.cpp

moc_player.o: moc_player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_player.o moc_player.cpp

moc_qmlmusicplugin.o: moc_qmlmusicplugin.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmlmusicplugin.o moc_qmlmusicplugin.cpp

moc_source.o: moc_source.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_source.o moc_source.cpp

moc_vlcsource.o: moc_vlcsource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_vlcsource.o moc_vlcsource.cpp

moc_spotifysource.o: moc_spotifysource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_spotifysource.o moc_spotifysource.cpp

moc_bansheesource.o: moc_bansheesource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_bansheesource.o moc_bansheesource.cpp

moc_auxsource.o: moc_auxsource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_auxsource.o moc_auxsource.cpp

moc_tracksource.o: moc_tracksource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tracksource.o moc_tracksource.cpp

####### Install

install_sources: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./ || $(MKDIR) $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./ 
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/sourcemanager.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./sourcemanager.cpp
	-$(INSTALL_FILE) /home/jlf/devel/qmlmusicplugin/mpris2tracklistproxy.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/mprisrootproxy.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprisrootproxy.cpp
	-$(INSTALL_FILE) /home/jlf/devel/qmlmusicplugin/mpris2rootproxy.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-$(INSTALL_FILE) /home/jlf/devel/qmlmusicplugin/mpris2playerproxy.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-$(INSTALL_FILE) /home/jlf/devel/qmlmusicplugin/mprisplayerproxy.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/mprissource.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprissource.cpp
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/mprisstatus.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprisstatus.cpp
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/player.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./player.cpp
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/qmlmusicplugin.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./qmlmusicplugin.cpp
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/source.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./source.cpp
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/mpris2source.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mpris2source.cpp
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/auxsource.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./auxsource.cpp
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/tracksource.cpp $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./tracksource.cpp
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/sourcemanager.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./sourcemanager.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/sourceoption.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./sourceoption.h
	-$(INSTALL_FILE) /home/jlf/devel/qmlmusicplugin/mpris2tracklistproxy.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/mprisrootproxy.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprisrootproxy.h
	-$(INSTALL_FILE) /home/jlf/devel/qmlmusicplugin/mpris2rootproxy.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/mpris2playerproxy.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mpris2playerproxy.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/mpris2source.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mpris2source.h
	-$(INSTALL_FILE) /home/jlf/devel/qmlmusicplugin/mprisplayerproxy.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/mprissource.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprissource.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/mprisstatus.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprisstatus.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/player.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./player.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/qmlmusicplugin.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./qmlmusicplugin.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/source.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./source.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/vlcsource.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./vlcsource.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/spotifysource.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./spotifysource.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/bansheesource.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./bansheesource.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/auxsource.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./auxsource.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/tracksource.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./tracksource.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/papafactory/details.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./details.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/papafactory/factory.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./factory.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/papafactory/papa_exception.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./papa_exception.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/papafactory/phactory.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./phactory.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/papafactory/singleton.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./singleton.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/papafactory/staticfactory.h $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./staticfactory.h
	-$(INSTALL_PROGRAM) /home/jlf/devel/qmlmusicplugin/qmlmusicplugin.pro $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./
	-strip $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./qmlmusicplugin.pro


uninstall_sources:  FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./sourcemanager.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mpris2tracklistproxy.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprisrootproxy.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mpris2rootproxy.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mpris2playerproxy.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprisplayerproxy.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprissource.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprisstatus.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./player.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./qmlmusicplugin.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./source.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mpris2source.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./auxsource.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./tracksource.cpp 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./sourcemanager.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./sourceoption.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mpris2tracklistproxy.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprisrootproxy.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mpris2rootproxy.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mpris2playerproxy.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mpris2source.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprisplayerproxy.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprissource.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./mprisstatus.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./player.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./qmlmusicplugin.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./source.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./vlcsource.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./spotifysource.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./bansheesource.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./auxsource.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./tracksource.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./details.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./factory.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./papa_exception.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./phactory.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./singleton.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./staticfactory.h 
	 -$(DEL_FILE) -r $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./qmlmusicplugin.pro
	-$(DEL_DIR) $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/./ 


install_target: first FORCE
	@$(CHK_DIR_EXISTS) $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/music/ || $(MKDIR) $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/music/ 
	-$(INSTALL_PROGRAM) "music/$(TARGET)" "$(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/music/$(TARGET)"
	-$(STRIP) --strip-unneeded "$(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/music/$(TARGET)"

uninstall_target:  FORCE
	-$(DEL_FILE) "$(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/music/$(TARGET)"
	-$(DEL_DIR) $(INSTALL_ROOT)/home/jlf/devel/qmlmusicplugin/music/ 


install:  install_sources install_target  FORCE

uninstall: uninstall_sources uninstall_target   FORCE

FORCE:

