/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -c Mpris2PlayerProxy -p mpris2playerproxy.h:mpris2playerproxy.cpp introspection/banshee_player.xml org.mpris.MediaPlayer2.Player
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mpris2playerproxy.h"

/*
 * Implementation of interface class Mpris2PlayerProxy
 */

Mpris2PlayerProxy::Mpris2PlayerProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

Mpris2PlayerProxy::~Mpris2PlayerProxy()
{
}

