/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -c MprisRootProxy -p mprisrootproxy.h:mprisrootproxy.cpp introspection/vlc_root.xml org.freedesktop.MediaPlayer
 *
 * qdbusxml2cpp is Copyright (C) 2011 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MPRISROOTPROXY_H_1324197705
#define MPRISROOTPROXY_H_1324197705

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.MediaPlayer
 */
class MprisRootProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.MediaPlayer"; }

public:
    MprisRootProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~MprisRootProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> Identity()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Identity"), argumentList);
    }

    inline QDBusPendingReply<QString> MprisVersion()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("MprisVersion"), argumentList);
    }

    inline QDBusPendingReply<> Quit()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Quit"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
